CREATE TABLE AUDIOGAME(ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    NAME VARCHAR(255),
    FOLDER VARCHAR(255));

CREATE TABLE AUDIOGAME_CHAPTER(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    AUDIOGAME_ID INTEGER,
    CHAPTER_NUM VARCHAR(255),
    CHAPTER_LINK VARCHAR(255),
    CHAPTER_NAME VARCHAR(1000),
    CHAPTER_TEXT VARCHAR(30000));

CREATE TABLE AUDIOGAME_SAVE(
    ID INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY(Start with 1, Increment by 1),
    AUDIOGAME_ID INTEGER,
    USERNAME VARCHAR(255),
    CHAPTER_NUM VARCHAR(255));